### PR TITLE
Fix StorageImage crash if Storage SDK isn't imported

### LINKED ISSUE #229: StorageImage component creates Uncaught TypeError: Object(...)(...).storage is not a function
### Version info

**React:** 
"react": "^0.0.0-experimental-235a6c4af",
    "react-dom": "^0.0.0-experimental-235a6c4af",

**Firebase:**
"firebase": "^7.10.0",

**ReactFire:**
"reactfire": "2.0.2",

**Other (e.g. Node, browser, operating system) (if applicable):**
Windows 10. Chrome 80

### Test case

Rendering a 

`<StorageImage
        storagePath='image.png'
      />`

by itself

### Steps to reproduce

Rendering a StorageImage component by itself in the DOM. The <App> is surrounded by <FirebaseAppProvider firebaseConfig={config}> tags

### Expected behavior

The image should load

### Actual behavior

Chrome DevTools prints out error and image does not load. Could it be a problem with my Firebase configuration? Thanks

`Uncaught TypeError: Object(...)(...).storage is not a function
    at StorageImage (index.js:47)
    at renderWithHooks (react-dom.development.js:15128)
    at mountIndeterminateComponent (react-dom.development.js:17905)
    at beginWork (react-dom.development.js:19257)
    at HTMLUnknownElement.callCallback (react-dom.development.js:187)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:236)
    at invokeGuardedCallback (react-dom.development.js:291)
    at beginWork$1 (react-dom.development.js:24079)
    at performUnitOfWork (react-dom.development.js:22998)
    at workLoopSync (react-dom.development.js:22928)
    at renderRootSync (react-dom.development.js:22891)
    at performConcurrentWorkOnRoot (react-dom.development.js:22236)
    at workLoop (scheduler.development.js:597)
    at flushWork (scheduler.development.js:552)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:164)`

### PR DESCRIPTION
**Pull request by jhuleatt**
fixes #229

### CODE REVIEW

File: reactfire/storage/index.tsx [hunk 1]
```diff
@@ -50,32 +43,19 @@ export function useStorageTask<T = unknown>(
...
-    React.DetailedHTMLProps<
-      React.ImgHTMLAttributes<HTMLImageElement>,
-      HTMLImageElement
-    >
-) {
+export function StorageImage(props: StorageImageProps & React.DetailedHTMLProps<React.ImgHTMLAttributes<HTMLImageElement>, HTMLImageElement>) {
   let { storage, storagePath, ...imgProps } = props;
 
-  storage = storage || useFirebaseApp().storage();
+  storage = storage || useStorage();
```
Comment (jhuleatt) [inline reactfire/storage/index.tsx]: this is the relevant change. everything else is just noise from changing our prettier config

**Comment by jhuleatt** [comment]
CI build passed, this follows the same pattern as Auth and others, I'm going to call it safe to merge.
